# Generated by Django 3.2.5 on 2021-07-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='listItems',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='list',
            name='recurring',
            field=models.CharField(max_length=255),
        ),
    ]
