# Generated by Django 3.2.5 on 2021-07-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210706_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='listItems',
            new_name='members',
        ),
    ]
